services:
  postgres:
    image: postgres:16-alpine
    container_name: trading_signal_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: trader
      POSTGRES_PASSWORD: trader_pass
      POSTGRES_DB: trading_signals
    ports:
      - '5434:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
